apiVersion : apps/v1
kind: Deployment
metadata:
  name: "coolapi-deployment"
  namespace: jtyrcoolapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "jtyrcoolapi"
  template:
    metadata:
      labels:
        app: "jtyrcoolapi"
    spec:
      containers:
        - name: "jtyrcoolapi"
          image: "jtyacrstan2022.azurecr.io/jtyrcoolapi:1.0.0"
          ports:
          - containerPort: 3000
