apiVersion: v1
kind: Service
metadata:
    name: "jtyrcoolapi-service"
    namespace: jtyrcoolapi
    labels:
        app: "jtyrcoolapi"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "jtyrcoolapi"
